### ISSUE TITLE
Correctly parse data from pyc files

### ISSUE THREAD

**Issue by dillonkh** [lextudio/pysnmp#157]
### Expected behavior

I expected builder.py to correctly read .pyc files instead of hard coding values for python versions that are not supported.
```
# pysnmp/smi/builder.py ln 90
if PY_MAGIC_NUMBER == pycData[:4]:
    pycData = pycData[4:]
    pycTime = struct.unpack("<L", pycData[:4])[0]
    pycData = pycData[4:]
    debug.logger & debug.FLAG_BLD and debug.logger(
        "file %s mtime %d" % (pycPath, pycTime)
    )
    break

 else:
    debug.logger & debug.FLAG_BLD and debug.logger(
        "bad magic in %s" % pycPath
    )
```
This code block is specifically expecting the header size to be 12 bytes, when the header size has been changed to 16 bytes since Python3.7.

### Actual behavior

When you try to use .pyc files you get the following error:
```
File "/blahblah/env/lib/python3.12/site-packages/pysnmp/smi/builder.py", line 127, in read
    return marshal.loads(pycData), pycSfx
                ^^^^^^^^^^^^^^^^^
ValueError: bad marshal data (unknown type code)
```
Note that this is just because there are 4 unexpected bytes being passed into `marshal.loads`. The issue can be fixed by correctly slicing out the header
```
if PY_MAGIC_NUMBER == pycData[:4]:
    pycTime = struct.unpack("<L", pycData[4:8])[0]
    pycData = pycData[16:]
    debug.logger & debug.FLAG_BLD and debug.logger(
        "file %s mtime %d" % (pycPath, pycTime)
    )
    break
```

### Detailed steps

My steps are somewhat hard to reproduce, im using `cx_Freeze` to build my binary. 
when i include `snmp` as a package (the way i would like it to be included)
```
build_exe_options = {
    "packages": ["pysnmp"]
}
```
I get the error.
My workaround is just including the non compiled .py files in my build, which works, but its strange that there is built in support for a version of Python that is not supported, and breaks for a supported version of python. 
```
pysnmp_dir = os.path.dirname(pysnmp.__file__)
build_exe_options = {
    "include_files": [(pysnmp_dir, "lib/pysnmp")]
}
```

### Python package information

7.1.14

### Operating system information

macOS, M2

### Python information

3.12.7

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://www.pysnmp.com/support#commercial-support), and then your reports are handled with higher priority after triage.

**Comment by dillonkh** [comment]
I know this issue was brought up here https://github.com/pysnmp/pysnmp/issues/50
I dont know why we would have support for old versions of python and not new. If the plan is to not support .pyc files at all I feel this logic should be removed.

**Comment by lextm** [comment]
The long-term plan is not yet determined, but we aren’t going to support loading .pyc files from a different Python version than the current one.

**Comment by dillonkh** [comment]
@lextm and by the current one you mean Python3.6? I was under the impression that `pysnmp` supported Python versions 3.9-3.12?

**Comment by dcvmoole** [comment]
> The long-term plan is not yet determined, but we aren’t going to support loading .pyc files from a different Python version than the current one.

I think something got lost in the https://github.com/pysnmp/pysnmp/issues/50 discussion on that front. The primary issue with the current code is the inability to achieve full loading performance of compiled MIBs. Pysnmp's implementation aims to support that the pysmi-generated modules are compiled to .pyc files, and will load them if their timestamps match. But, that is currently entirely broken.

The format for .pyc files that is in use as of Python 3.7 is specified in PEP-552. All Python versions supported by pysnmp therefore use PEP-552 as well. However, the format for .pyc files implemented in the pysnmp code right now is the pre-3.7 format. Thus, the current code is broken for everyone, including the common case that they use the _same_ Python version to both compile and load their MIBs. As such, this issue has nothing to do with loading files generated with a different Python version.

As one example: the .pyc feature reduces the load time of the MIBs that I use from about three seconds to under one second - a very noticeable difference. However, I currently have to change the pysnmp code to use the proper format in order to get that speed-up.

Note that the change proposed by @dillonkh is also not correct, as PEP-552 moves the timestamp field to the third word rather than the second. The simplest fix is to change both instances of the following line currently present in the code:

> pycData = pycData[4:]

to:

> pycData = pycData[8:]

That's it. I can turn that into a pull request if it helps. Note that that only supports the timestamp-based variant described in PEP-552, but that would be enough for basically everyone right now. Please note that a highly similar snippet of code is present in pysmi, which has the same issues and can be fixed in the same way.

Long term, there are a few possible options here. Please allow me to quickly sketch the possible solutions, as far as I am aware:

1. Remove support for .pyc files altogether. I for one would not be happy with this, as the performance gain is substantial.
2. Change the current code to support PEP-552 in a minimal way. That is the solution I sketched above.
3. Change the current code to support PEP-552 properly, including support for hash checking when requested. That is still a relatively small change. It is unlikely that the extra support will be beneficial for a whole lot of people, though.
4. Change the code to use Python's high-level module loading mechanism, by means of importlib. That leaves the handling of module compilation and .pyc files entirely to Python itself (including where those files are placed etc.). That is a generally much better approach. However, it runs into the problem that the pysmi-generated code expects global variables to be set at module load time. As far as I can tell, setting global variables as part of the high-level module loading mechanism is _possible_  (see links below) but not documented anywhere, and thus not necessarily future proof.
5. Change the pysmi-generated code to wrap all statements in the context of a function, so that that function can be called with the same arguments that were previously global variables. This is the most invasive change but will also produce the most future-proof/maintainable overall outcome.

Some StackOverflow links regarding solutions 4 and 5:
- https://stackoverflow.com/questions/67631
- https://stackoverflow.com/questions/2601047
- https://stackoverflow.com/questions/42542214
- https://stackoverflow.com/questions/47199554
- https://stackoverflow.com/questions/24054097
- https://stackoverflow.com/questions/38647348

For what it is worth, my recommendation/request would be to apply solution 2 now and look into the best approach between solutions 4 and 5 in the longer term. I would be happy to help out if needed.

**Comment by lextm** [comment]
@dcvmoole Other options out there so I don't want to rush to a quick solution (while option 2 you proposed might be something many users prefer).

For example, if the code changes so that only .py files are loaded by default, but users can override that and load .pyc files on their own. That leaves the maintenance of special code to end users, other than us, and might be more flexible and future proof.

**Comment by lextm** [comment]
Since this is Python, end users can easily modify the behavior by overriding `read` using the example below,

``` python

from pysnmp.smi import builder
import marshal
import sys
# Other imports here

def custom_read(self, f):
    pycTime = pyTime = -1

    # Your own code to process .pyc and .py files based on __AbstractMibSource.read.

    if pycTime != -1 and pycTime >= pyTime:
        return marshal.loads(pycData), pycSfx

    if pyTime != -1:
        modData, pyPath = self._get_data(f + pySfx, "r")
        return compile(modData, pyPath, "exec"), pyPath

    raise OSError(ENOENT, "No suitable module found", f)

builder.DirMibSource.read = custom_read
```
