### ISSUE TITLE
Traps storm handling

### ISSUE THREAD

**Issue by atolikin94** [lextudio/pysnmp#8]
A question - in case there are ~10k switches sending traps at the same time, pysnmp won't be able to handle all of them and some of them will be dropped, right?
Is there any indication that a server receives more traps that it could handle and some of the traps will be dropped?

**Comment by lextm** [comment]
This is not a question specific to SNMP TRAP, because if you send lots of UDP packets (any protocol) to the system the same situation happens.

The operating system and the network adapter driver will first take care of the packets and drop whatever they cannot handle, so your Python app and PySNMP do not have control on the dropped ones. The only thing on your side is to ensure the Python app reads the packets out as soon as possible, which is challenging as PySNMP wasn't written for that purpose (mentioned by Ilya in several places).

Thus, it is recommended that you move to something else that is designed for such scenarios (C/C++ based SNMP trap receivers for example).
